version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pos-app
    container_name: pos-Hub
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=new_pos
      - DB_USERNAME=root
      - DB_PASSWORD=

  db:
    image: mysql:8.0
    container_name: pos-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: new_pos
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
